config/routes.rb
RailsApp::Application.routes.draw do
  resources :tsgs
  
  faye_server '/faye', timeout: 25 do 
    map '/report' => RealtimeReportController
    map default: :block
  end

  get "front/index"
  root to: "front#index"

end

app/models/chat_message.rb
class ChatMessage
  HISTORY = 20

  attr_accessor :message, :created_at

  def initialize(message, created_at=Time.now)
    @message = message
    @created_at = created_at
    self.class.push self
  end

  def self.push(chat_message)
    @chat_messages ||= []
    @chat_messages << chat_message
    @chat_messages = @chat_messages.reverse.take(HISTORY).reverse
  end

  def self.find
    @chat_messages ||= []
  end
end

app/models/message_record.rb
class MessageRecord < ActiveRecord::Base
	HISTORY = 20
  	attr_accessible :title, :tsg_id, :type_id

  	belongs_to :tsg

#  	scope :recent, where(:all).reverse_order.limit(HISTORY)
	scope :recent, order('id desc').limit(10)
end

app/models/tsg.rb
class Tsg < ActiveRecord::Base
  attr_accessible :department, :name

  has_many :message_records
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/front_controller.rb
class FrontController < ApplicationController
  def index
#  	@chat_messages = ChatMessage.find
  	@chat_messages = MessageRecord.all
#  	@chat_messages = MessageRecord.recent
	@tsgs = Tsg.all
  end
end

app/controllers/tsgs_controller.rb
class TsgsController < ApplicationController
  # GET /tsgs
  # GET /tsgs.json
  def index
    @tsgs = Tsg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tsgs }
    end
  end

  # GET /tsgs/1
  # GET /tsgs/1.json
  def show
    @tsg = Tsg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tsg }
    end
  end

  # GET /tsgs/new
  # GET /tsgs/new.json
  def new
    @tsg = Tsg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tsg }
    end
  end

  # GET /tsgs/1/edit
  def edit
    @tsg = Tsg.find(params[:id])
  end

  # POST /tsgs
  # POST /tsgs.json
  def create
    @tsg = Tsg.new(params[:tsg])

    respond_to do |format|
      if @tsg.save
        format.html { redirect_to @tsg, notice: 'Tsg was successfully created.' }
        format.json { render json: @tsg, status: :created, location: @tsg }
      else
        format.html { render action: "new" }
        format.json { render json: @tsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tsgs/1
  # PUT /tsgs/1.json
  def update
    @tsg = Tsg.find(params[:id])

    respond_to do |format|
      if @tsg.update_attributes(params[:tsg])
        format.html { redirect_to @tsg, notice: 'Tsg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tsg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tsgs/1
  # DELETE /tsgs/1.json
  def destroy
    @tsg = Tsg.find(params[:id])
    @tsg.destroy

    respond_to do |format|
      format.html { redirect_to tsgs_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/front_helper.rb
module FrontHelper
end

app/helpers/tsgs_helper.rb
module TsgsHelper
end

app/views/front/index.html.haml
.container
	.message	
		%ul#chat
			/ - @chat_messages.each do |chat_message|
			/ 	%li.item#report
			/ 		= chat_message.created_at.strftime('%-d/%-m/%Y %k:%M:%S')
			/ 		= ':'
			/ 		= chat_message.title
			/ 		= ':'
			/ 		= chat_message.tsg.department

			- @tsgs.each do |tsg|
				%li.tsg
					= tsg.name
					%ul
						- tsg.message_records.each do |chat_message|
							%li.item#report
								= chat_message.created_at.strftime('%-d/%-m/%Y %k:%M:%S')
								= ':'
								= chat_message.title
								= ':'
								= chat_message.tsg.department
	%hr

	.opt
		.submitbox	
			%select
				- @tsgs.each do |tsg|
					%option{value: '#{tsg.name}'} #{tsg.name}
			%input{type: 'text', name: 'message'}
			%button Post
	%hr

	.footer
		%ul

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tsgs/_form.html.haml
= form_for @tsg do |f|
  - if @tsg.errors.any?
    #error_explanation
      %h2= "#{pluralize(@tsg.errors.count, "error")} prohibited this tsg from being saved:"
      %ul
        - @tsg.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :department
    = f.text_field :department
  .actions
    = f.submit 'Save'

app/views/tsgs/edit.html.haml
%h1 Editing tsg

= render 'form'

= link_to 'Show', @tsg
\|
= link_to 'Back', tsgs_path

app/views/tsgs/index.html.haml
%h1 Listing tsgs

%table
  %tr
    %th Name
    %th Department
    %th
    %th
    %th

  - @tsgs.each do |tsg|
    %tr
      %td= tsg.name
      %td= tsg.department
      %td= link_to 'Show', tsg
      %td= link_to 'Edit', edit_tsg_path(tsg)
      %td= link_to 'Destroy', tsg, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tsg', new_tsg_path

app/views/tsgs/new.html.haml
%h1 New tsg

= render 'form'

= link_to 'Back', tsgs_path

app/views/tsgs/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @tsg.name
%p
  %b Department:
  = @tsg.department

= link_to 'Edit', edit_tsg_path(@tsg)
\|
= link_to 'Back', tsgs_path